language: csharp
mono: none
dotnet: 2.2.203
dist: xenial
script:
  - dotnet build -c Release
  - mon=`date +%m`
  - day=`date +%d`
  - dotnet pack "DragonFruit.Six.Locale/DragonFruit.Six.Locale.csproj" /p:PackageVersion=2019.$mon.$day -o .. -c Release 
  - dotnet nuget push "*.nupkg" --api-key "$nugetkey" --source "https://api.nuget.org/v3/index.json"