os: windows
language: shell

stages:
  - name: deploy
    if: type = push AND fork = false AND env(nuget_key) IS present

before_script:
  - choco install visualstudio2019-workload-netcorebuildtools
  - powershell Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Force

jobs:
  include:       
  - stage: deploy
    name: "NuGet"
    script: powershell -File Deploy.ps1
    if: branch = master
