os: windows
language: bash

before_script:
  - choco install dotnetcore
  - set version=(powershell Get-Date -UFormat "%Y.%m.%d.%h")
script:
  - dotnet restore ".\DragonFruit.Six.Locale.sln"
  - dotnet pack ".\DragonFruit.Six.Locale\DragonFruit.Six.Locale.csproj" -o "..\" -c Release -p:PackageVersion=%version%.%TRAVIS_BUILD_NUMBER%
  - dotnet push *.nupkg -k %NUGET_KEY% -s "https://api.nuget.org/v3/index.json" --skip-duplicate -n
