language: csharp
mono: latest
dist: xenial
script:
  - msbuild DragonFruit.Six.Locale.sln /p:Configuration=Release
  - mon=`date +%m`
  - day=`date +%d`
  - nuget pack "DragonFruit.Six.Locale/DragonFruit.Six.Locale.csproj" /p:PackageVersion=2019.$mon.$day -o .. -c Release 
  - nuget push "*.nupkg" -ApiKey "$nugetkey" -Source "https://api.nuget.org/v3/index.json"