os: windows
language: shell

before_script:
  - choco install visualstudio2019-workload-netcorebuildtools
script:
  - powershell Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Force
  - powershell -File Deploy.ps1
