os: windows
language: shell

branches:
  only:
  - master

before_script:
  - choco install visualstudio2019-workload-netcorebuildtools
  - choco install nuget.commandline
script:
  - powershell Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Force
  - powershell -File Deploy.ps1
